[Variables]

;==========================================================Font
Font=方正水黑简体
Size=15
Color=255,255,255
;==========================================================


;===================================CLASSICO
Class1ICO=Image (14)
Class2ICO=Image (22)
Class3ICO=Image (11)
Class4ICO=Image (8)
Class5ICO=Image (12)
;===================================


;=========================================================Class1APP1-7
Class1APP1Name=计算器
Class1APP1Ico=Image (15)
Class1App1Path=C:\Windows\System32\calc.exe

Class1APP2Name=计算器
Class1APP2Ico=Image (15)
Class1App2Path=C:\Windows\System32\calc.exe

Class1APP3Name=Welcome
Class1APP3Ico=Image (15)
Class1App3Path=C:\Windows\System32\calc.exe

Class1APP4Name=Welcome
Class1APP4Ico=Image (15)
Class1App4Path=C:\Windows\System32\calc.exe

Class1APP5Name=Welcome
Class1APP5Ico=Image (15)
Class1App5Path=C:\Windows\System32\calc.exe

Class1APP6Name=Welcome
Class1APP6Ico=Image (15)
Class1App6Path=C:\Windows\System32\calc.exe

Class1APP7Name=Welcome
Class1APP7Ico=Image (15)
Class1App7Path=C:\Windows\System32\calc.exe
;==========================================================


;=========================================================Class2APP1-7
Class2APP1Name=Welcome
Class2APP1Ico=Image (15)
Class2App1Path=C:\Windows\System32\calc.exe

Class2APP2Name=Welcome
Class2APP2Ico=Image (15)
Class2App2Path=C:\Windows\System32\calc.exe

Class2APP3Name=Welcome
Class2APP3Ico=Image (15)
Class2App3Path=C:\Windows\System32\calc.exe

Class2APP4Name=Welcome
Class2APP4Ico=Image (15)
Class2App4Path=C:\Windows\System32\calc.exe

Class2APP5Name=Welcome
Class2APP5Ico=Image (15)
Class2App5Path=C:\Windows\System32\calc.exe

Class2APP6Name=Welcome
Class2APP6Ico=Image (15)
Class2App6Path=C:\Windows\System32\calc.exe

Class2APP7Name=Welcome
Class2APP7Ico=Image (15)
Class2App7Path=C:\Windows\System32\calc.exe
;==========================================================


;=========================================================Class3APP1-7
Class3APP1Name=Welcome
Class3APP1Ico=Image (15)
Class3App1Path=C:\Windows\System32\calc.exe

Class3APP2Name=Welcome
Class3APP2Ico=Image (15)
Class3App2Path=C:\Windows\System32\calc.exe

Class3APP3Name=Welcome
Class3APP3Ico=Image (15)
Class3App3Path=C:\Windows\System32\calc.exe

Class3APP4Name=Welcome
Class3APP4Ico=Image (15)
Class3App4Path=C:\Windows\System32\calc.exe

Class3APP5Name=Welcome
Class3APP5Ico=Image (15)
Class3App5Path=C:\Windows\System32\calc.exe

Class3APP6Name=Welcome
Class3APP6Ico=Image (15)
Class3App6Path=C:\Windows\System32\calc.exe

Class3APP7Name=Welcome
Class3APP7Ico=Image (15)
Class3App7Path=C:\Windows\System32\calc.exe
;==========================================================


;=========================================================Class4APP1-7
Class4APP1Name=Welcome
Class4APP1Ico=Image (15)
Class4App1Path=C:\Windows\System32\calc.exe

Class4APP2Name=Welcome
Class4APP2Ico=Image (15)
Class4App2Path=C:\Windows\System32\calc.exe

Class4APP3Name=Welcome
Class4APP3Ico=Image (15)
Class4App3Path=C:\Windows\System32\calc.exe

Class4APP4Name=Welcome
Class4APP4Ico=Image (15)
Class4App4Path=C:\Windows\System32\calc.exe

Class4APP5Name=Welcome
Class4APP5Ico=Image (15)
Class4App5Path=C:\Windows\System32\calc.exe

Class4APP6Name=Welcome
Class4APP6Ico=Image (15)
Class4App6Path=C:\Windows\System32\calc.exe

Class4APP7Name=Welcome
Class4APP7Ico=Image (15)
Class4App7Path=C:\Windows\System32\calc.exe
;==========================================================


;=========================================================Class5APP1-7
Class5APP1Name=Welcome
Class5APP1Ico=Image (15)
Class5App1Path=C:\Windows\System32\calc.exe

Class5APP2Name=Welcome
Class5APP2Ico=Image (15)
Class5App2Path=C:\Windows\System32\calc.exe

Class5APP3Name=Welcome
Class5APP3Ico=Image (15)
Class5App3Path=C:\Windows\System32\calc.exe

Class5APP4Name=Welcome
Class5APP4Ico=Image (15)
Class5App4Path=C:\Windows\System32\calc.exe

Class5APP5Name=Welcome
Class5APP5Ico=Image (15)
Class5App5Path=C:\Windows\System32\calc.exe

Class5APP6Name=Welcome
Class5APP6Ico=Image (15)
Class5App6Path=C:\Windows\System32\calc.exe

Class5APP7Name=Welcome
Class5APP7Ico=Image (15)
Class5App7Path=C:\Windows\System32\calc.exe
;==========================================================
